name       : chrome-gnome-shell
version    : '9.0'
release    : 4
source     :
    - https://git.gnome.org/browse/chrome-gnome-shell/snapshot/chrome-gnome-shell-9.tar.xz : 11fdfaa12208ec87ddbac27fc9652609c74e421d3e258de6b4776e392efdd448
license    : GPL-3.0
component  : desktop.gnome
summary    : GNOME Shell integration for Chrome
description: |
    Web extension for Google Chrome/Chromium, Vivaldi, Opera (and other
    WebExtensions capable browsers) and native host messaging connector
    that provides integration with GNOME Shell and the corresponding
    extensions repository https://extensions.gnome.org.
builddeps  :
    - jq
rundeps    :
    - python-gobject2
    - python-requests
    - python-dbus
    - python
build      : |
    %cmake -DBUILD_EXTENSION=OFF
install    : |
    %make_install
