name       : chrome-gnome-shell
version    : '10.1'
release    : 6
source     :
    - git|https://gitlab.gnome.org/GNOME/chrome-gnome-shell.git : 4ddb52e095566a7fab8049bf265d4c9b42f2031f
license    : GPL-3.0
component  : desktop.gnome
summary    : GNOME Shell integration for Chrome
description: |
    Web extension for Google Chrome/Chromium, Vivaldi, Opera (and other
    WebExtensions capable browsers) and native host messaging connector
    that provides integration with GNOME Shell and the corresponding
    extensions repository https://extensions.gnome.org.
builddeps  :
    - jq
rundeps    :
    - python-gobject2
    - python-requests
    - python-dbus
    - python
build      : |
    %cmake -DBUILD_EXTENSION=OFF
install    : |
    %make_install
    # Yes, Chrome really does need to be put into /etc/opt. I know.
    install -Dm00644 $workdir/contrib/policies/chrome-gnome-shell.json $installdir/etc/opt/chrome/policies/managed/chrome-gnome-shell.json
    install -Dm00644 $workdir/contrib/policies/chrome-gnome-shell.json $installdir/etc/chromium/policies/managed/chrome-gnome-shell.json
